"""update

Revision ID: cee5d62dbb36
Revises: 746a487a0ec6
Create Date: 2025-02-03 16:00:25.286711

"""
from alembic import op
import models as models
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cee5d62dbb36'
down_revision = '746a487a0ec6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subscribed_tenant_id_list', sa.ARRAY(models.types.StringUUID()), server_default='{8ac8bdea-550b-48a3-9672-e8afd06476ce}', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_column('subscribed_tenant_id_list')

    # ### end Alembic commands ###
