"""update

Revision ID: aa2dab0542e7
Revises: a91b476a53de
Create Date: 2025-02-02 17:04:11.849450

"""
from alembic import op
import models as models
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa2dab0542e7'
down_revision = 'a91b476a53de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('apps', schema=None) as batch_op:
        batch_op.add_column(sa.Column('publish_path', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('publish_status', sa.String(length=255), server_default=sa.text("'normal'::character varying"), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('apps', schema=None) as batch_op:
        batch_op.drop_column('publish_status')
        batch_op.drop_column('publish_path')

    # ### end Alembic commands ###
