"""update

Revision ID: 746a487a0ec6
Revises: aa2dab0542e7
Create Date: 2025-02-02 21:54:36.835713

"""
from alembic import op
import models as models
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '746a487a0ec6'
down_revision = 'aa2dab0542e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=255), server_default='normal', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_column('role')

    # ### end Alembic commands ###
